### ISSUE TITLE
Create Class class

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#14]
Basic class for storage for now. Will add more functionality later.

## Tasks
- [ ] Create Class class
- [ ] Can store basic class things #2 
- [ ] Able to Get and Set (You can either make the members public or user getters/setters, I don't care)

## Notes
Basic for now. To be expanded upon and used by other Activities.

## Blocks
None
