### ISSUE TITLE
View a Class

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#15]
Activity and layout for viewing a class. Make it pretty!

## Tasks
- [ ] View basic class info
- [ ] Looks nice
- [ ] Able to add more info later
- [ ] Buttons (maybe put it in the action menu?)
  - [ ] Edit button (blocked)
  - [ ] Add Task (functionality TBA)
  - [ ] View Meetings (functionality TBA)

## Notes
Use the Class class #14 

## Blocks
- [ ] #14
