### ISSUE TITLE
HomePage design

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#16]
Fix up the homepage.

## Tasks
- [x] Replace the classes with a recycler view
  - [x] Shows basic information
    - Use the same card the view_all_classes activity uses
- [x] Fix the constraints on the elements
- [x] Fix the sizing on the elements
- [x] Button to view all classes

## Notes
Basic functionality, nothing fancy. Yet.

## Blocks
None
