### ISSUE TITLE
View All Classes Activity

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#17]
Create an Activity and Layout for viewing all Classes.

## Tasks
- [x] Create a Layout
  - [x] Able to view a list of classes
    - [x] Probably just shows course code, section, year, and term
- [x] Create an Activity
  - [x] Loads all classes from the Class singleton
    - See #13 
  - [x] Able to click a class to view it
    - See #8 

## Notes
Probably use a Recycler view. Nothing else really works.

## Blocks
- [x] #13 
  - Needs the singleton for the Activity, (can still make layout though)
- [x] #8 
  - Calls this activity when clicking a Class
