### ISSUE TITLE
Create EditableClass Layout and NewClass

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#2]
Create a basic activity for creating a *New Class*.
Create and design a _Layout_ for displaying a Class's info through editable fields.

## Tasks
- [x] Create a new Activity
  - [x] Should have a new Layout file
- [x] Class Code (text) (ABCD-1234)
- [x] Full Name (text)
- [x] Section (integer)
- [x] Description (paragraph)
- [x] Professor (text)
- [x] OK Button
- [x] Cancel button
- [ ] OK and Cancel go back

## Notes
Remember that more info will be added later.
Keep that in mind when designing, for exampling you could implement a scrollview or use top/left anchoring.

## Blocks
None
