### ISSUE TITLE
Testing Architectures

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#22]
Why wont this shhtuff work?

## Tasks
- [x] It builds
- [x] It finds all tests
- [x] It runs the tests
- [ ] GitHub status check with the tests

## Notes
Wont even run, annoying errors. Time for Google.

## Blocks
None

**Comment by FaceInCake** [comment]
later
