### ISSUE TITLE
View Task

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#27]
Layout and activity to view a task.

## Tasks
- [x] Create a layout
  - [x] An InfoSection for each member of Task
    - [x] Unique IDs for each section
    - [x] Sections are named
    - [x] Unique Icon for each section
    - (You can look at ViewClass to see how it works)
- [x] Find views
  - InfoSection is the type of the info sections
- [x] Takes in a `tid` int
  - [x] Async query for given task
  - [x] onUI fill out the fields
    - Use the InfoSection.setValue(String)
- [x] Action menu for edit and delete
  - [x] No functionality for now
