### ISSUE TITLE
View All Tasks

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#28]
Layout and activity able to view a list of tasks.

## Tasks
- [x] Layout
  - [x] RecView of tasks
  - [x] Create another layout for the card of the task
  - [x] Probably just name, class it's for, and due date in the bottom right
  - [x] OnClick, startActivity viewTask, pass in a `tid`
- [x] Activity
  - [x] Get a `cid` int extra
    - [x] If `cid` was given, query all tasks that belong to that class
    - [x] If not given, query all tasks
  - [x] Async update fields
