### ISSUE TITLE
New Task

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#29]
Activity and layout for creating a new task.

## Tasks
- [x] Layout
  - [x] Editable views for each member of Task
  - [x] OK & Cancel button
  - [x] Unique IDs
- [x] Activity
  - [x] Get `cid` int extra
    - [x] If none given, alertError and finish()
  - [x] Init views
  - [x] OK attempts to insert the task and finishes the activity
  - [x] Cancel finishes the activity
