### ISSUE TITLE
Design EditableTask Layout and Create NewTask Activity

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#3]
Create an activity for a _New Task_.
Create and design a _Layout_ for a task. They should be editable fields.

## Tasks
- [x] Create a new Layout file
- [x] Type (Assignment / Quiz / Test / Exam / Project)
- [x] Name (text)
- [x] Description (paragraph)
- [x] Open (datetime) (default to now if not filled)
- [x] Due (datetime)
- [x] Location (text)
- [x] OK button
- [x] Cancel button
- [x] OK button and Cancel button goes back

## Notes
Remember that there are some solid template activities to work off of.
Remember that there is more info to be added. So make sure to design it so that is can easily be modified later.
Like implementing a scrollview or using top/left anchors.

## Blocks
None
