### ISSUE TITLE
New Meeting

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#30]
Activity and layout for creating a meeting time

## Tasks
- [x] Layout
  - [x] Editable view for each member of Meeting
  - [x] OK & Cancel button
  - [x] Unique IDs
- [x] Activity
  - [x] Get `cid` int extra
    - [x] If none given, alertError and finish()
  - [x] Init views
  - [x] OK attempts to insert the meeting and finishes the activity
  - [x] Cancel finishes the activity
