### ISSUE TITLE
View Meeting

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#31]
Layout and activity to view a meeting.

## Tasks
- [x] Layout
  - [x] An InfoSection for each member of Meeting
    - [x] Unique IDs for each section
    - [x] Sections are named
    - [x] Unique Icon for each section
    - (You can look at ViewClass to see how it works)
- [x] Activity
  - [x] Init views
    - InfoSection is the type of the info sections
- [x] Takes in a `mid` int
  - [x] Async query for given meeting
  - [x] onUI fill out the fields
    - Use the InfoSection.setValue(String)
- [x] Action menu for edit and delete
  - [x] No functionality for now
