### ISSUE TITLE
View All Meetings

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#32]
Layout and activity able to view a list of meetings.

## Tasks
- [x] Layout
  - [x] RecView of meetings
  - [x] Create another layout for the card of the meeting
  - [x] Probably just type and section, class it's for, abbreviate the weekdays, and then start time
  - [x] OnClick, startActivity viewMeeting, pass in a `mid`
- [x] Activity
  - [x] Get a `cid` int extra
    - [x] If `cid` was given, query all meetings that belong to that class
    - [x] If not given, query all meetings
  - [x] Async update fields
