### ISSUE TITLE
Delete functionality

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#33]
Enable all the delete buttons to work

## Tasks
- [x] On delete, attempt deletion, toast, and finish()
  - [x] One in ViewClass
  - [x] One in ViewTask
  - [x] One in ViewMeeting
