### ISSUE TITLE
Edit Class functionality

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#34]
You'll have to do some decision making.
You can either make a new activity and layout start from scratch.
You can also modify NewClass slightly, and just subclass it, taking in a class from the extras to prefill the fields.
Those are just two ideas, think it through.

## Tasks
- [x] Edit button in ViewClass works
- [x] Able to edit things
- [x] Updates into database
