### ISSUE TITLE
Edit Task functionality

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#35]
You'll have to do some decision making.
Similar to #34, take a look.

## Tasks
- [x] Edit button in ViewTask works
- [x] Able to edit things
- [x] Updates into database
