### ISSUE TITLE
Edit Meeting Functionality

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#36]
You'll have to do some decision making.
Similar to #34, take a look.

## Tasks
- [x] Edit button in ViewMeeting works
- [x] Able to edit things
- [x] Updates into database
