### ISSUE TITLE
Edit the settings layout

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#4]
Under res/xml is root_preferences.xml. You can edit this to design the settings.

## Tasks
- [x] User preferences section
  - [x] Dark mode / Light mode
  - [x] Show weekends
  - [x] Hide days with no events
- [x] School Info section
  - [x] School name
  - [x] School Address
  - [x] Apply button
  - [x] Cancel button

## Notes
Edit root_preferences.xml under res/xml. It's also used to grab default values.
It currently has some examples. Be sure to delete them once you no longer need them, _along with the string resources they made_.

Remember that more info will be added later. Make sure more fields can be added later.

## Blocks
None
