### ISSUE TITLE
Design a HomePage Layout

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#5]
Create and design Home Page _Layout_ file. Most of the buttons won't work yet.

## Tasks
- [x] Rename the MainActivity _layout_ and _activity_ (Make sure to use the refactor thing so stuff doesn't break)
- [x] Button to view all Events
- [x] Button to view all Classes
- [x] Button to view settings

## Notes
Remember that we plan to a Calendar view, grade view, and an upcoming event preview to the home page.
You can incorporate them now, or just make some room for them later.
You can do a fancy drawer pullout. Might be better to keep it simple for now.

## Blocks
None
