### ISSUE TITLE
View Class Activity

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/ThePrincipleApp#8]
Similar to #6. But no editable fields. Make it look pretty.

## Tasks
- [x] Create new Activity and Layout
- [x] Layout displays all class info
- [x] Uses the Class class (take from bundle)
- [x] Looks nice
- [x] Able to add more info later
- [x] Buttons (maybe put it in the action menu?)
  - [x] Edit button (functionality TBA)
    - #2 
  - [x] Add Task (functionality TBA)
    - #3 
  - [x] View Meetings (functionality TBA)

## Notes
Simple issue. Feel free to be verbose with displaying information.

## Blocks
- [x] #13 
  - Displays information from this object
